#!/bin/bash

#PBS -P RDS-FEI-FTP-RW
#PBS -l select=3:ncpus=32:mem=120GB
#PBS -l walltime=150:00:00
#PBS -N FerryILP
#PBS -m abe
#PBS -M llin7797@uni.sydney.edu.au

module load python/3.12.2 magma/2.5.3 pandas/2.0.3 gurobi/9.1.2
source /project/RDS-FEI-FTP-RW/envs/amod/bin/activate
cd /project/RDS-FEI-FTP-RW/FerryILP
python ILPimplementation/main.py > output_simpleB_heuristic2_2.log 2> error_simpleB_heuristic2_2.log
